### ISSUE TITLE
Add basic information on register page

### ISSUE THREAD

**Issue by taitus** [devmasdemocracia/masdemocraciaeu#61]
# What
Add static basic information provided by customer on register page.

# How
Add table with information at the bottom of the page.

![new registration](https://user-images.githubusercontent.com/16189/41929040-5941789e-7977-11e8-812a-6473b054b0cd.png)

**Comment by taitus** [comment]
@agileontheweb Can you check responsive versions and styles of this page? you have a 🎁  as css-inline on `/users/registrations/new.html.erb`

**Comment by taitus** [comment]
@agileontheweb Branch name: basic-information

**Comment by Senen** [comment]
@agileontheweb this is your next issue! Tomorrow we can talk about it at morning meeting.

**Comment by Senen** [comment]
Closed via #77
