### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by taitus** [devmasdemocracia/masdemocraciaeu#7]
# What
Modify home page to try explain "Mas democracia en Europa". I think this page needs to be more beautiful than explanatory. It should be keep in mind that on application only have proposals.

We need to ask to customer the information wanted to be  shown at new home page.

**Comment by Senen** [comment]
@agileontheweb  Here we have project description to get a better idea of the objectives of this application, i think we should reflect these concepts at new home page design.

Tell me when you have read the document so we can talk a little bit about best way to do a new design.

**Comment by agileontheweb** [comment]
@Senen , @taitus 
Perfectly, I'm going to read the document to get an idea and discuss the layout together.

**Comment by Senen** [comment]
Closed via #71
