### ISSUE TITLE
Customer Suggestions

### ISSUE THREAD

**Issue by taitus** [devmasdemocracia/masdemocraciaeu#74]
# What

- [x] Registro en nombre de colectivo/asociación: obligatorio el campo de Teléfono (para poder confirmar)
- [x] En el correo de confirmación de registro dice te damos la bievenida al Portal de Gobierno abierto. Debería decir a la plataforma Más democracia en Europa
- [x]  Cuando accedes al Menú/pestaña de Propuestas, el texto que aparece destacado, está también subrayado como si tuviera un hipervínculo. Quitar ese subrayado. 
- [x] El periodo de presentación de propuestas finaliza el 30 de septiembre.
- [x] El apartado de Ayuda sobre las propuestas que aparece abajo en la página hay que eliminarlo de todas las páginas.
- [x] Revisar textos: Propuestas retiradas (formulario)
- [x] Hemos quedado que desactivamos la página de comunidad.
- [x] Se van a añadir 2 botones grandes en la barra lateral derecha de la página de una propuesta:
    - [x] Uno “Crea una propuesta complementaria” que llevará a un nuevo formulario de creación de propuesta (Propuesta complementaria)
    - [x] Uno “Sugiere cambios en la propuesta” que llevará a la zona de comentarios de la propuesta.  (Sugiere cambios)
- [ ] Título de la propuesta: El título debe ser breve. Se trata de describir tu propuesta de modo que suscite interés. ACOTAR Nº PALABRAS: 20 PALABRAS
- [x] Objetivo/s concreto/s: Todas las propuestas incluidas en esta plataforma tratan de una forma o de otra de mejorar la democracia en Europa. Es importante que tu propuesta tenga algunos objetivos más concretos dentro de ese gran objetivo común. 
- [x] ¿Es factible tu propuesta?: Explica brevemente cómo puede llevarse la propuesta a la práctica, incluyendo si es posible una estimación, aún en términos generales, de su coste.  (AÑADIR EL PUNTO AL FINAL)
- [x] Imagen descriptiva: Puedes subir una imagen en los formatos: jpeg, jpg, y de hasta 1 MB por archivo.(TAL VEZ HABRÍA QUE INDICAR CUÁLES SON LAS MEDIDAS, NO SOLO EL PESO DE LAS IMÁGENES)
- [x] Palabras clave: Es recommendable (QUITAR UNA M) seleccionar o crear algunas palabras clave para identificar tu propuesta. Puedes elegir entre las palabras clave existentes o introducir las que desees separadas por una coma (',').
- [x] Selecciona aquí las palabras clave:  – SI QUEREMOS UNIFICAR, TENDRÍAMOS QUE PONER EN TODAS PARTES CATEGORÍAS/PALABRAS CLAVE, PARA FACILITAR LA COMPRENSIÓN DE TODO EL MUNDO
- [x] Y EN EL BOTÓN DE DEBAJO DEL TODO, DEL FORMULARIO, EN VEZ DE CREAR PROPUESTA, DECIR ENVÍA TU PROPUESTA
- [x] En ANTES DE COMENZAR A REDACTAR TU PROPUESTA: Incluir el signo de interrogación antes de comenzar estas preguntas:
- [x] Has comprobado si la propuesta, o alguna propuesta muy similar, se ha puesto ya en práctica? Es conveniente reflexionar uns minutos sobre ello, y hacer una consulta en Internet usando palabras clave. --> Yo aquí cambiaría la consulta en internet por consultas en MasDemocraciaEnEuropa para asegurarse de que busca en propuestas. Si buscan en internet les pueden salir enlaces a otras aplicaciones web y páginas mejor posicionadas …. no me arriesgaría.
- [x] Has comprobado si existe una propuesta similar en esta plataforma? Busca propuestas en esta plataforma usando palabras clave. AÑADIR AQUÍ BOTÓN/ENLACE AL BUSCADOR
- [x] En el texto ¿De qué se trata? --> Resaltar con negritas lo que marcamos y añadir los hipervínculos correspondientes
- [x] En la versión en inglés, en el formulario, en vez de Create new proposal, Create a proposal. También, abajo en este formulario, por unificar con el castellano, decir, Send your proposal
- [x] Faltan un par de textos en inglés que os enviamos enseguida. Ojo, los cambios que hemos pedido (como añadir lo de crea una propuesta complementaria, etc.), también tienen que ir en inglés.

**Comment by Senen** [comment]
All done via #76 and #75
