### ISSUE TITLE
Footer section

### ISSUE THREAD

**Issue by taitus** [devmasdemocracia/masdemocraciaeu#8]
# What
Check footer section and remove leftover text. I should keep the "Open government" section and expect more information from the client.

# How
Remove text referenced to:
  - Participation
  - Transparency
  - Open data
  - Add LinkedIn icon, link and translations. We will need a new setting entry called "linkdein_handle" to make this configurable from admin panel. For now social link should point to EsGlobal social media accounts.

**Comment by Senen** [comment]
Closed via #35
