### ISSUE TITLE
Fix text size on navbar

### ISSUE THREAD

**Issue by taitus** [devmasdemocracia/masdemocraciaeu#80]
# What
Check text size on navbar "Más democracia en europa". Can be reproduced by adjusting the width of the screen.

# Screenshot
![captura de pantalla 2018-07-18 a las 12 23 33](https://user-images.githubusercontent.com/16189/42876060-cb81a8c4-8a85-11e8-8ab0-b3c4d8c93e89.png)

**Comment by agileontheweb** [comment]
@taitus 
I add screenshots of how I see now on various devices. 

--------------------------------------------------------

![schermata 2018-07-19 alle 09 20 23](https://user-images.githubusercontent.com/1497150/42927505-06ab3c9e-8b35-11e8-8d44-e919e74d1bea.png)

![schermata 2018-07-19 alle 09 20 17](https://user-images.githubusercontent.com/1497150/42927506-06c9dd2a-8b35-11e8-9a2d-2255e2e55609.png)

![schermata 2018-07-19 alle 09 22 28](https://user-images.githubusercontent.com/1497150/42927631-5ace5734-8b35-11e8-9dae-3e0195313e52.png)

![schermata 2018-07-19 alle 09 22 20](https://user-images.githubusercontent.com/1497150/42927632-5af5d2b4-8b35-11e8-8cd4-503342c84dda.png)

![schermata 2018-07-19 alle 09 23 39](https://user-images.githubusercontent.com/1497150/42927670-792c2f6c-8b35-11e8-807a-0d06e2e076ed.png)

![schermata 2018-07-19 alle 09 23 34](https://user-images.githubusercontent.com/1497150/42927671-7948413e-8b35-11e8-836e-94f6495b6452.png)

--------------------------------------------------------

**DESKTOP**
![schermata 2018-07-19 alle 09 24 52](https://user-images.githubusercontent.com/1497150/42927724-a666c80c-8b35-11e8-8369-41ee88b1312a.png)

![schermata 2018-07-19 alle 09 25 22](https://user-images.githubusercontent.com/1497150/42927749-b0ad2658-8b35-11e8-87e7-5ef093badf7b.png)

--------------------------------------------------------

**WATCH THIS**
The button overlaps
I create a new branch or I arrange it in this one?!
If I create a new branch I do the pull request of this.

![trasferimento](https://user-images.githubusercontent.com/1497150/42927877-131ff57c-8b36-11e8-8a04-e3b13b644bbf.png)

**Comment by Senen** [comment]
The same behaviour is happening at original consul repo so i think it's better to wait for a solution from Consul/core team.

**Comment by agileontheweb** [comment]
@taitus @Senen 
If we want to solve this problem, the quick solution I can change the size of the text.
Example.
![schermata 2018-07-19 alle 11 09 57](https://user-images.githubusercontent.com/1497150/42933166-635903ae-8b44-11e8-9067-d156d92049f0.png)

**Comment by taitus** [comment]
Close via #81
