### ISSUE TITLE
Sitemap.xml output

### ISSUE THREAD

**Issue by Senen** [devmasdemocracia/masdemocraciaeu#89]
# Objective 
Fix sitemap.xml output. Currently is showing disabled features urls and other empty pages.

# How

# Current Sitemap output
<urlset xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"><url><loc>https://www.masdemocraciaeneuropa.org</loc><lastmod>2018-07-21T05:00:06+00:00</lastmod><changefreq>always</changefreq><priority>1.0</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/general_terms</loc><lastmod>2018-07-21T05:00:06+00:00</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/help</loc><lastmod>2018-07-21T05:00:06+00:00</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/help/how-to-use</loc><lastmod>2018-07-21T05:00:06+00:00</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/help/faq</loc><lastmod>2018-07-21T05:00:06+00:00</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/debates</loc><lastmod>2018-07-21T05:00:06+00:00</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/proposals</loc><lastmod>2018-07-21T05:00:06+00:00</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/proposals/7-bases-de-datos-para-la-implementacion-y-evaluacion-de-politicas-publicas</loc><lastmod>2018-07-11T15:24:32+02:00</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/proposals/8-esto-es-una-prueba-de-propuesta-complementaria</loc><lastmod>2018-07-11T15:39:23+02:00</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/proposals/9-creacion-de-mecanismos-sancionadores-con-efectos-vinculantes</loc><lastmod>2018-07-13T15:37:26+02:00</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/proposals/10-ue-para-sus-habitantes</loc><lastmod>2018-07-13T16:04:34+02:00</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/proposals/11-vincular-el-mundo-academico-con-el-sector-privado-y-la-administracion-publica</loc><lastmod>2018-07-17T12:18:12+02:00</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/budgets</loc><lastmod>2018-07-21T05:00:06+00:00</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/polls</loc><lastmod>2018-07-21T05:00:06+00:00</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://www.masdemocraciaeneuropa.org/legislation/processes</loc><lastmod>2018-07-21T05:00:06+00:00</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url></urlset>

**Comment by taitus** [comment]
Close via #92
